[workspace]
members = [
    "rs/hang",
    "rs/libmoq",
    "rs/moq-cli",
    "rs/moq-clock",
    "rs/moq-lite",
    "rs/moq-mux",
    "rs/moq-native",
    "rs/moq-relay",
    "rs/moq-token",
    "rs/moq-token-cli",
]
resolver = "2"

[workspace.dependencies]
hang = { version = "0.14", path = "rs/hang" }
moq-lite = { version = "0.14", path = "rs/moq-lite" }
moq-mux = { version = "0.2", path = "rs/moq-mux" }
moq-native = { version = "0.13", path = "rs/moq-native", default-features = false }
moq-token = { version = "0.5", path = "rs/moq-token" }

serde = { version = "1", features = ["derive"] }
tokio = "1.48"
web-async = { version = "0.1.1", features = ["tracing"] }
web-transport-iroh = "0.2"
web-transport-proto = "0.5"
web-transport-quiche = "0.2"
web-transport-quinn = "0.11"
web-transport-trait = "0.3.2"
web-transport-ws = "0.2.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
